### ISSUE TITLE
Error with CGO

### ISSUE THREAD

**Issue by favadi** [google/godepq#18]
The error happens when CGO is imported.

```
Error: cannot find package "C" in any of:
    /usr/local/go/src/C (from $GOROOT)
    /var/lib/jenkins/workspace/test/godepq/src/C (from $GOPATH)
    /var/lib/jenkins/workspace/test/godeps/src/C
    /var/lib/jenkins/workspace/test/src/C
```

I guess we can easily fix by adding "C" to ignore list. But I wonder are there more packages like "C" we should do the same to?

**Comment by timstclair** [comment]
Hmm, it's supposed to already be ignored: https://github.com/google/godepq/blob/9daed838e20afbaf2f0b4dcd3afd26630b104e88/pkg/deps.go#L65

I suspect it's being resolved to something else after the refactoring.

**Comment by timstclair** [comment]
I wasn't able to reproduce this

**Comment by favadi** [comment]
I can reproduce it in our CI node. I confirm that 0273292 (before the refactor) works fine. I will try to setup a test to reproduce this.

**Comment by favadi** [comment]
@timstclair I created #19 and can reproduce the error every time with this steps.
- build latest godepq binary (at this time is 9daed838e20afbaf2f0b4dcd3afd26630b104e88)
- execute 

```
./godepq -from github.com/google/godepq/testing/d
Error: cannot find package "C" in any of:
    /opt/local/lib/go/src/C (from $GOROOT)
    /Users/favadi/go/src/C (from $GOPATH)
```

What I expected: "C" package is ignored and godepq reports that there is no dependency in package github.com/google/godepq/testing/d.

What it did: return an error about can not find package "C".

**Comment by timstclair** [comment]
Thanks. Turns out I was using an older binary when I said I couldn't reproduce it :/

**Comment by dmitshur** [comment]
Use [binstale](https://godoc.org/github.com/shurcooL/binstale). :P

**Comment by favadi** [comment]
Sorry for lack of feedback, I confirmed that the problem is fixed in master branch.
